### ISSUE TITLE
Possível erro no registro 1100

### ISSUE THREAD

**Issue by CyberV2** [Samuel-Oliveira/Java-Efd-Contribuicoes#3]
Acredito que existe um erro na linha 24 do "GerarRegistro1100" (linkada abaixo)
https://github.com/Samuel-Oliveira/Java-Efd-Contribuicoes/blob/da29df5694e27024df3aeda579936c792fac0815/src/main/java/br/com/swconsultoria/efd/contribuicoes/bo/bloco1/GerarRegistro1100.java#L24C68-L24C68
O valor do campo "VL_CRED_APU" está sendo incluído duas vezes, acredito que o correto seria substituir o getVl_cred_apu por getVl_tot_cred_apu.
Acredito que este problema não foi detectado anteriormente pois, pelo menos nos casos que acompanhei, o campo Vl_cred_ext_apu normalmente tem valor zero.

**Comment by Samuel-Oliveira** [comment]
Opa Blz? Obrigado por avisar!
Corrigido na versao 1.32.1
